export enum EntityActionType {
  LIST = 'ENTITY:LIST',
  CREATE = 'ENTITY:CREATE',
  UPDATE = 'ENTITY:UPDATE',
  REMOVE = 'ENTITY:REMOVE',
  NEXT_PAGE = 'ENTITY:NEXT_PAGE',
  PREV_PAGE = 'ENTITY:PREV_PAGE',
}
