export enum EntityActionType {
  LIST = 'ENTITY:LIST',
  CREATE = 'ENTITY:CREATE',
  UPDATE = 'ENTITY:UPDATE',
  REMOVE = 'ENTITY:REMOVE',
  READ = 'ENTITY:READ',
}

export enum EntityHelperActionType {
  GO_TO_PAGE = 'ENTITY:GO_TO_PAGE',
  INVALIDATE_QUERY = 'ENTITY:INVALIDATE_QUERY',
}
